apiVersion: v1
kind: Secret
metadata:
  name: lanchonete-secret
  namespace: ns-lanchonete
type: Opaque
data:
  datasource_username: dXNlcl9maWFw
  datasource_password: cGFzc3dvcmRfZmlhcA==
  access_token: VEVTVC0xODE5OTQzMDI4NzU1NDM4LTEwMDgyMS1jZTUyNGJhMzc4ZWQ0ZGUyZjFlNWM2ZDg2MGU0MzYwNy04MjgzMDQyMA==