apiVersion: v1
kind: ConfigMap
metadata:
  name: app-lanchonete-configmap
  namespace: ns-lanchonete
data:
  datasource_url: jdbc:postgresql://rds-lanchoente-tf.cnawis8ysgvo.us-east-1.rds.amazonaws.com:5432/lanchonete
  ngrok_url: https://0ab6-189-110-173-172.ngrok-free.app/ #Atualizar ngrok para testes de integração