apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::180294201352:role/eks-service-role
      username: eks-service-role
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::180294201352:user/github-actions-k8s-infra
      username: eks-admin
      groups:
        - system:masters
