name: Deploy Kubernetes Infra

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Iniciando com credenciais adicionadas anteriormente
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install Kubectl (generic installation method)
      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6`1

      # Terraform Execution
      - name: Terraform Init
        run: |
          terraform init -reconfigure

      - name: Terraform Format
        run: |
          terraform fmt

      - name: Terraform Plan
        run: |
          terraform plan

        # Extraindo os outputs após o apply
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
          terraform output -json > terraform_outputs.json

      # Coletando informação do output
      - name: Extract Terraform Outputs
        id: extract_outputs
        run: |
          export ACCESS_KEY_ID=$(jq -r '.eks_user_access_key_id.value' terraform_outputs.json)
          export SECRET_ACCESS_KEY=$(jq -r '.eks_user_secret_access_key.value' terraform_outputs.json)
          echo "ACCESS_KEY_ID=$ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" >> $GITHUB_ENV

      # Atualizando GitHub Secrets
      - name: Update GitHub Secrets
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO=${{ github.repository }}
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"encrypted_value":"'$ACCESS_KEY_ID'"}' \
            https://api.github.com/repos/$REPO/actions/secrets/AWS_ACCESS_KEY_ID

          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"encrypted_value":"'$SECRET_ACCESS_KEY'"}' \
            https://api.github.com/repos/$REPO/actions/secrets/AWS_SECRET_ACCESS_KEY

      # Reconfigurando AWS Credentials com as novas credenciais
      - name: Configure AWS credentials (Updated)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name EKS-fiap-tech-challenge --region us-east-1

      - name: Deploy Application
        run: |
          kubectl apply -f k8s/00-ns-lanchonete.yaml
          kubectl apply -f k8s/10-secret-lanchonete.yaml
          kubectl apply -f k8s/11-app-lanchonete-configmap.yaml
          kubectl apply -f k8s/21-app-lanchonete-service.yaml
          kubectl apply -f k8s/41-app-lanchonete-deployment.yaml

      # Terraform destroy
      - name: Terraform Destroy
        if: always()
        run: |
          terraform destroy -auto-approve
